name: Auto Start

on:

  push:
    branches:
      - main
  schedule:
  - cron: "30 * * * *" # See https://crontab.guru/#0_7,9,11,17,20_*_*_*

jobs:
  auto_run:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3     
      - name: Install depedency 
        run: pip install -r install.txt
      - name: Run
        run: |
          python run.py
          
